Repository glotaran/pyglotaran, pull requests merged in 2020-11, with the labels that each got.

#445 Add tooling to improve docs
  .pre-commit-config.yaml
  CONTRIBUTING.rst
  docs/source/conf.py
  pyproject.toml
  setup.cfg
Labels: doc, tooling

#451 Improve CI
  .github/dependabot.yml
  .github/workflows/CI_CD_actions.yml
Labels: tooling

#452 Change pyupgrade flag from '--py36-plus' to '--py38-plus'
  .pre-commit-config.yaml
Labels: tooling

#453 Refactor glotaran.model
  glotaran/__init__.py
  glotaran/model/__init__.py
  glotaran/model/attribute.py
  glotaran/model/base_model.py
  glotaran/model/dataset_descriptor.py
  glotaran/model/decorator.py
  glotaran/model/property.py
  glotaran/model/weight.py
  glotaran/parse/register.py
Labels: enhancement

#456 Fix 'not valid as a type' type checking errors
  glotaran/analysis/simulation.py
  glotaran/builtin/models/kinetic_image/__init__.py
  glotaran/builtin/models/kinetic_image/kinetic_image_result.py
  glotaran/builtin/models/kinetic_spectrum/__init__.py
  glotaran/builtin/models/kinetic_spectrum/kinetic_spectrum_model.py
  glotaran/builtin/models/kinetic_spectrum/kinetic_spectrum_result.py
  glotaran/builtin/models/kinetic_spectrum/spectral_constraints.py
  glotaran/builtin/models/kinetic_spectrum/spectral_penalties.py
  glotaran/builtin/models/kinetic_spectrum/spectral_relations.py
  glotaran/model/attribute.py
Labels: Typing, enhancement

#459 Run test_optimization in single-threaded dask mode
  glotaran/analysis/test/test_optimization.py
Labels: bug, enhancement

#463 Add workflow to generate and upload doxygen documentation
  .github/workflows/doxygen.yml
  docs/Doxyfile.ini
Labels: tooling

#464 Fix strange behaviour of interrogate hook
  .pre-commit-config.yaml
Labels: tooling

#465 Remove legacy python versions as target from black config
  pyproject.toml
Labels: tooling
