Repository glotaran/pyglotaran, pull requests merged in 2020-12, with the labels that each got.

#442 Refactor/optimization
  docs/source/quickstart.rst
  glotaran/analysis/matrix_calculation.py
  glotaran/analysis/optimize.py
  glotaran/analysis/problem.py
  glotaran/analysis/problem_bag.py
  glotaran/analysis/residual_calculation.py
  glotaran/analysis/scheme.py
  glotaran/analysis/test/mock.py
  glotaran/analysis/test/test_grouping.py
  glotaran/analysis/test/test_optimization.py
  glotaran/analysis/test/test_problem.py
  glotaran/builtin/models/doas/__init__.py
  glotaran/builtin/models/doas/doas_matrix.py
  glotaran/builtin/models/doas/doas_megacomplex.py
  glotaran/builtin/models/doas/doas_model.py
  glotaran/builtin/models/doas/doas_result.py
  glotaran/builtin/models/doas/doas_spectral_matrix.py
  glotaran/builtin/models/doas/oscillation.py
  glotaran/builtin/models/doas/test/test_doas_model.py
  glotaran/builtin/models/kinetic_image/kinetic_image_result.py
  glotaran/builtin/models/kinetic_image/test/test_kinetic_image_model.py
  glotaran/builtin/models/kinetic_spectrum/kinetic_spectrum_model.py
  glotaran/builtin/models/kinetic_spectrum/kinetic_spectrum_result.py
  glotaran/builtin/models/kinetic_spectrum/spectral_penalties.py
  glotaran/builtin/models/kinetic_spectrum/spectral_relations.py
  glotaran/builtin/models/kinetic_spectrum/test/test_coherent_artifact.py
  glotaran/builtin/models/kinetic_spectrum/test/test_kinetic_spectrum_model.py
  glotaran/builtin/models/kinetic_spectrum/test/test_spectral_constraints.py
  glotaran/builtin/models/kinetic_spectrum/test/test_spectral_irf.py
  glotaran/builtin/models/kinetic_spectrum/test/test_spectral_penalties.py
  glotaran/builtin/models/kinetic_spectrum/test/test_spectral_relations.py
  glotaran/model/base_model.py
  glotaran/model/decorator.py
  glotaran/parse/test/test_model_parser_doas.py
  glotaran/parse/test/test_model_spec_doas.yml
  pyproject.toml
  setup.py
Labels: enhancement

#467 Add stubs for runtime patched objects
  .pre-commit-config.yaml
  glotaran/builtin/models/kinetic_image/initial_concentration.pyi
  glotaran/builtin/models/kinetic_image/irf.pyi
  glotaran/builtin/models/kinetic_image/k_matrix.pyi
  glotaran/builtin/models/kinetic_image/kinetic_image_dataset_descriptor.pyi
  glotaran/builtin/models/kinetic_image/kinetic_image_megacomplex.pyi
  glotaran/builtin/models/kinetic_image/kinetic_image_model.pyi
  glotaran/builtin/models/kinetic_spectrum/kinetic_spectrum_dataset_descriptor.pyi
  glotaran/builtin/models/kinetic_spectrum/kinetic_spectrum_model.py
  glotaran/builtin/models/kinetic_spectrum/kinetic_spectrum_model.pyi
  glotaran/builtin/models/kinetic_spectrum/spectral_constraints.pyi
  glotaran/builtin/models/kinetic_spectrum/spectral_irf.pyi
  glotaran/builtin/models/kinetic_spectrum/spectral_penalties.pyi
  glotaran/builtin/models/kinetic_spectrum/spectral_relations.pyi
  glotaran/builtin/models/kinetic_spectrum/spectral_shape.pyi
  glotaran/model/base_model.pyi
  glotaran/model/dataset_descriptor.pyi
  pyproject.toml
  requirements_dev.txt
Labels: Typing

#477 Fix for incompatible types in spectral_relations
  glotaran/builtin/models/kinetic_spectrum/spectral_penalties.py
  glotaran/builtin/models/kinetic_spectrum/test/test_spectral_penalties.py
Labels: bug
