Repository glotaran/pyglotaran, pull requests merged in 2021-03, with the labels that each got.

#589 Refactor io plugins
  glotaran/__init__.py
  glotaran/builtin/io/ascii/wavelength_time_explicit_file.py
  glotaran/builtin/io/csv/csv.py
  glotaran/builtin/io/netCDF/netCDF.py
  glotaran/builtin/io/sdt/sdt_file_reader.py
  glotaran/builtin/io/sdt/test/test_file_readers.py
  glotaran/builtin/io/yml/yml.py
  glotaran/cli/commands/optimize.py
  glotaran/cli/commands/pluginlist.py
  glotaran/io/__init__.py
  glotaran/io/decorator.py
  glotaran/io/interface.py
  glotaran/io/io.py
  glotaran/io/register.py
  pyproject.toml
  setup.cfg
Labels: Type: Refactor, python

#592 Make ParameterGroup.markdown() indepedent of order parametergroups were added
  glotaran/parameter/parameter_group.py
  glotaran/parameter/test/test_parameter_group.py
Labels: Type: Enhancement

#595 Add configs for tools planned to use
  setup.cfg
Labels: Type: Tooling

#596 Move doc dependencies to a separate file
  .github/workflows/CI_CD_actions.yml
  docs/requirements.txt
  readthedocs.yml
  requirements_dev.txt
Labels: Type: Tooling

#600 Refactor plugin system
  .coveragerc
  .github/CODEOWNERS
  .github/workflows/CI_CD_actions.yml
  .gitignore
  docs/Makefile
  docs/make.bat
  docs/remove_notebook_written_data.py
  docs/source/conf.py
  docs/source/index.rst
  docs/source/notebooks/plugin_system/plugin_howto_write_a_io_plugin.ipynb
  docs/source/notebooks/quickstart/model.yaml
  docs/source/notebooks/quickstart/parameters.yaml
  docs/source/notebooks/quickstart/quickstart.ipynb
  docs/source/plugin_dev.rst
  docs/source/user_documentation/using_plugins.rst
  glotaran/__init__.py
  glotaran/builtin/io/ascii/wavelength_time_explicit_file.py
  glotaran/builtin/io/csv/csv.py
  glotaran/builtin/io/netCDF/netCDF.py
  glotaran/builtin/io/sdt/sdt_file_reader.py
  glotaran/builtin/io/sdt/test/test_file_readers.py
  glotaran/builtin/io/yml/test/test_save_result.py
  glotaran/builtin/io/yml/yml.py
  glotaran/builtin/models/kinetic_spectrum/test/test_kinetic_spectrum_model.py
  glotaran/builtin/models/kinetic_spectrum/test/test_spectral_irf.py
  glotaran/cli/commands/optimize.py
  glotaran/cli/commands/pluginlist.py
  glotaran/io/__init__.py
  glotaran/io/decorator.py
  glotaran/io/interface.py
  glotaran/io/project.py
  glotaran/io/register.py
  glotaran/model/__init__.py
  glotaran/model/decorator.py
  glotaran/model/register.py
  glotaran/model/test/test_register.py
  glotaran/parameter/test/test_parameter.py
  glotaran/parameter/test/test_parameter_group.py
  glotaran/plugin_system/__init__.py
  glotaran/plugin_system/base_registry.py
  glotaran/plugin_system/data_io_registration.py
  glotaran/plugin_system/io_plugin_utils.py
  glotaran/plugin_system/model_registration.py
  glotaran/plugin_system/project_io_registration.py
  glotaran/plugin_system/test/test_base_registry.py
  glotaran/plugin_system/test/test_data_io_registration.py
  glotaran/plugin_system/test/test_io_plugin_utils.py
  glotaran/plugin_system/test/test_model_registration.py
  glotaran/plugin_system/test/test_project_io_registration.py
  pyproject.toml
  requirements_dev.txt
  setup.cfg
  tox.ini
Labels: Type: Enhancement, Type: Refactor, python

#602 Add a Zenodo config file
  .zenodo.json
Labels: Priority: Medium, Status: In Progress, Type: Release preparation, Type: Tooling

#618 Maintenance/forward port v0.3.3 changes
  .zenodo.json
  HISTORY.rst
  README.md
  glotaran/__init__.py
  glotaran/analysis/problem.py
  glotaran/builtin/models/kinetic_spectrum/spectral_penalties.py
Labels: Priority: High, Status: Resolved, Type: Bug
