Repository glotaran/pyglotaran, pull requests merged in 2021-02, with the labels that each got.

#533 Refactor tests to address code duplication
  glotaran/builtin/models/kinetic_spectrum/test/test_kinetic_spectrum_model.py
  glotaran/builtin/models/kinetic_spectrum/test/test_spectral_irf.py
Labels: enhancement

#541 Apply black, pyupgrade and flake8 on stub files
  .pre-commit-config.yaml
  glotaran/__init__.py
  glotaran/builtin/file_formats/ascii/__init__.py
  glotaran/builtin/file_formats/sdt/__init__.py
  glotaran/builtin/models/kinetic_image/__init__.py
  glotaran/builtin/models/kinetic_image/initial_concentration.pyi
  glotaran/builtin/models/kinetic_image/irf.pyi
  glotaran/builtin/models/kinetic_image/k_matrix.pyi
  glotaran/builtin/models/kinetic_image/kinetic_image_dataset_descriptor.pyi
  glotaran/builtin/models/kinetic_image/kinetic_image_megacomplex.pyi
  glotaran/builtin/models/kinetic_image/kinetic_image_model.pyi
  glotaran/builtin/models/kinetic_spectrum/__init__.py
  glotaran/builtin/models/kinetic_spectrum/kinetic_spectrum_dataset_descriptor.pyi
  glotaran/builtin/models/kinetic_spectrum/kinetic_spectrum_model.pyi
  glotaran/builtin/models/kinetic_spectrum/spectral_constraints.pyi
  glotaran/builtin/models/kinetic_spectrum/spectral_irf.pyi
  glotaran/builtin/models/kinetic_spectrum/spectral_penalties.pyi
  glotaran/builtin/models/kinetic_spectrum/spectral_relations.pyi
  glotaran/builtin/models/kinetic_spectrum/spectral_shape.pyi
  glotaran/examples/__init__.py
  glotaran/model/__init__.py
  glotaran/model/base_model.pyi
  glotaran/model/dataset_descriptor.pyi
  tox.ini
Labels: Typing, tooling

#540 Fixed arguments in Result's get_scheme call
  glotaran/analysis/result.py
  glotaran/analysis/test/test_optimization.py
Labels: bug

#547 Fix typo in Levenberg-Marquardt
  glotaran/analysis/optimize.py
  glotaran/analysis/scheme.py
  glotaran/analysis/test/test_optimization.py
Labels: refactor

#548 Refactor/531 address deprecation warnings
  glotaran/builtin/models/kinetic_spectrum/test/test_coherent_artifact.py
  glotaran/builtin/models/kinetic_spectrum/test/test_spectral_irf.py
Labels: bug

#546 Change LICENSE to LGPLv3
  LICENSE
  setup.py
Labels: enhancement, tooling

#543 Updated README and HISTORY in preparation for 0.3.0 release
  HISTORY.rst
  README.md
Labels: doc, enhancement

#555 Upgrade Code for numpy 1.20 compatibility
  glotaran/analysis/test/models.py
  glotaran/builtin/file_formats/sdt/test/test_file_readers.py
  glotaran/parameter/parameter.py
  requirements_dev.txt
  setup.py
Labels: Priority: Medium, Status: In Progress, Type: Refactor, dependencies

#560 Change setup
  .pre-commit-config.yaml
  CONTRIBUTING.rst
  requirements_dev.txt
  setup.cfg
  setup.py
Labels: Priority: Low, Status: In Progress, Type: Tooling

#557 Add Feature/321 parameter history
  glotaran/analysis/optimize.py
  glotaran/analysis/problem.py
Labels: Priority: Medium, Status: In Progress, Type: Enhancement

#563 Remove 'docs' artifact from CI, in favor of RTD build on PR
  .github/workflows/CI_CD_actions.yml
Labels: Priority: Low, Status: In Progress, Type: Tooling

#567 Update to codeowners
  .github/CODEOWNERS
Labels: Priority: Medium, Status: In Progress, Type: Tooling

#575 Fix for excessive memory usage when creating results
  glotaran/analysis/problem.py
  glotaran/io/prepare_dataset.py
Labels: Priority: High

#571 Replace model.py -> model.yml
  docs/source/quickstart.rst
Labels: Type: Documentation

#569 Prepare v0.3.1 release
  HISTORY.rst
  glotaran/__init__.py
Labels: Type: Release preparation

#576 Fix excessive memory usage in _create_svd
  glotaran/analysis/problem.py
  glotaran/io/prepare_dataset.py
Labels: Priority: Medium, Status: Resolved, Type: Bug, python

#568 Use a notebook for quickstart
  .github/workflows/CI_CD_actions.yml
  .github/workflows/trigger-binder.yml
  .gitignore
  .pre-commit-config.yaml
  README.md
  binder/environment.yml
  binder/postBuild
  docs/source/conf.py
  docs/source/index.rst
  docs/source/notebooks/model.yaml
  docs/source/notebooks/parameters.yaml
  docs/source/notebooks/quickstart.ipynb
  docs/source/quickstart.rst
  docs/strip_empty_notebook_cells.py
  pyproject.toml
  requirements_dev.txt
  tox.ini
Labels: Priority: Medium, Status: Resolved, Type: Documentation, Type: Tooling

#580 Forwardport release info from 0.3.2 release
  HISTORY.rst
Labels: Type: Documentation

#573 ⬆️ UPGRADE: Autoupdate pre-commit config
  .pre-commit-config.yaml
Labels: Priority: Low, dependencies
