Repository glotaran/pyglotaran, pull requests merged in 2021-09, with the labels that each got.

#797 🩹 False positive model validation fail when combining multiple default megacomplexes
  glotaran/model/dataset_model.py
  glotaran/model/dataset_model.pyi
  glotaran/model/megacomplex.py
  glotaran/model/test/test_dataset_model.py
Labels: Type: Serious Bug, Type: Bug

#760 🧪🚇 Add integration test result validation (maintain/0.4.1)
  .github/test_result_consistency.py
  .github/workflows/integration-tests.yml
  .gitignore
  CONTRIBUTING.rst
  requirements_dev.txt
  tox.ini
Labels: Type: Tooling

#754 🧪🚇 Add integration test result validation
  .github/test_result_consistency.py
  .github/workflows/integration-tests.yml
  .gitignore
  CONTRIBUTING.rst
  requirements_dev.txt
  tox.ini
Labels: Type: Tooling

#803 🚀 Prepare release 0.4.1
  changelog.md
Labels: Type: Release preparation

#772 🔧 Use flake8-print in pre-commit
  .pre-commit-config.yaml
  glotaran/analysis/test/test_constraints.py
  glotaran/analysis/test/test_optimization.py
  glotaran/analysis/test/test_penalties.py
  glotaran/analysis/test/test_problem.py
  glotaran/analysis/test/test_relations.py
  glotaran/builtin/io/ascii/wavelength_time_explicit_file.py
  glotaran/builtin/io/yml/test/test_model_parser.py
  glotaran/builtin/megacomplexes/damped_oscillation/test/test_doas_model.py
  glotaran/builtin/megacomplexes/spectral/test/test_spectral_model.py
  glotaran/model/test/test_model.py
  glotaran/test/test_spectral_decay.py
  glotaran/test/test_spectral_decay_full_model.py
  glotaran/test/test_spectral_penalties.py
  tox.ini
Labels: Type: Tooling

#805 🧪 Add more tools from the 'pygrep-hooks' pre-commit hook
  .pre-commit-config.yaml
  glotaran/deprecation/deprecation_utils.py
Labels: Type: Tooling

#807 Refactor model.from_dict to parse megacomplex_type from dict and add simple_generator for testing
  .pre-commit-config.yaml
  benchmark/pytest/analysis/test_problem.py
  glotaran/builtin/io/yml/yml.py
  glotaran/builtin/megacomplexes/decay/test/test_decay_megacomplex.py
  glotaran/model/model.py
  glotaran/testing/__init__.py
  glotaran/testing/model_generators.py
  glotaran/testing/plugin_system.py
  glotaran/testing/test/__init__.py
  glotaran/testing/test/test_model_generators.py
  glotaran/testing/test/test_plugin_system.py
  requirements_dev.txt
  setup.cfg
Labels: Type: Refactor

#831 🚇 Retarget PR benchmarks to main
  .github/workflows/pr_benchmark.yml
Labels: Type: Tooling

#843 🩹 Fix parameter expression parsing
  glotaran/parameter/parameter.py
  glotaran/parameter/parameter_group.py
  glotaran/parameter/test/test_parameter.py
Labels: Type: Serious Bug, Priority: High
