Repository glotaran/pyglotaran, pull requests merged in 2022-01, with the labels that each got.

#959 🔧🚇 Exclude test files from duplication checks on sonarcloud
  .sonarcloud.properties
  changelog.md
Labels: Type: Tooling

#958 🚧📚 Add changes of PR 860 to changelog
  changelog.md
Labels: Type: Documentation

#960 ⬆️🔧 Update pre-commit
  .pre-commit-config.yaml
  glotaran/utils/sanitize.py
Labels: Type: Tooling

#866 Feature: Generators
  .github/CODEOWNERS
  changelog.md
  docs/source/notebooks/plugin_system/plugin_howto_write_a_io_plugin.ipynb
  docs/source/notebooks/quickstart/quickstart.ipynb
  glotaran/__init__.py
  glotaran/builtin/io/folder/test/test_folder_plugin.py
  glotaran/builtin/io/yml/test/test_save_model.py
  glotaran/builtin/io/yml/test/test_save_result.py
  glotaran/builtin/io/yml/test/test_save_scheme.py
  glotaran/builtin/io/yml/yml.py
  glotaran/deprecation/deprecation_utils.py
  glotaran/deprecation/modules/examples/__init__.py
  glotaran/deprecation/modules/examples/sequential.py
  glotaran/deprecation/modules/test/test_changed_imports.py
  glotaran/deprecation/modules/test/test_model_model.py
  glotaran/deprecation/modules/test/test_parameter_parameter_group.py
  glotaran/deprecation/modules/test/test_project_result.py
  glotaran/deprecation/modules/test/test_project_scheme.py
  glotaran/deprecation/test/dummy_package/__init__.py
  glotaran/deprecation/test/dummy_package/deprecated_module_attribute.py
  glotaran/deprecation/test/test_deprecation_utils.py
  glotaran/examples/__init__.py
  glotaran/examples/sequential.py
  glotaran/examples/test/test_example.py
  glotaran/model/test/test_model.py
  glotaran/project/generators/__init__.py
  glotaran/project/generators/generator.py
  glotaran/project/generators/test/test_genenerate_decay_model.py
  glotaran/project/test/test_result.py
  glotaran/testing/model_generators.py
  glotaran/testing/simulated_data/__init__.py
  glotaran/testing/simulated_data/parallel_spectral_decay.py
  glotaran/testing/simulated_data/sequential_spectral_decay.py
  glotaran/testing/simulated_data/shared_decay.py
  glotaran/testing/test/test_example.py
  glotaran/testing/test/test_model_generators.py
Labels: Type: Enhancement

#981 🚇👌 Run Doxygen workflow only on 'workflow_dispatch'
  .github/workflows/doxygen.yml
Labels: Type: Tooling

#896 ✨ Add parameter IO support for more formats supported by pandas
  .github/CODEOWNERS
  .pre-commit-config.yaml
  changelog.md
  glotaran/builtin/io/csv/__init__.py
  glotaran/builtin/io/csv/csv.py
  glotaran/builtin/io/pandas/__init__.py
  glotaran/builtin/io/pandas/csv.py
  glotaran/builtin/io/pandas/test/data/reference_parameters.csv
  glotaran/builtin/io/pandas/test/data/reference_parameters.ods
  glotaran/builtin/io/pandas/test/data/reference_parameters.tsv
  glotaran/builtin/io/pandas/test/data/reference_parameters.xlsx
  glotaran/builtin/io/pandas/test/data/reference_parameters.yaml
  glotaran/builtin/io/pandas/test/test_pandas_parameters.py
  glotaran/builtin/io/pandas/tsv.py
  glotaran/builtin/io/pandas/xlsx.py
  glotaran/parameter/parameter_group.py
  glotaran/parameter/test/test_parameter_group.py
  glotaran/plugin_system/test/test_project_io_registration.py
  glotaran/utils/io.py
  glotaran/utils/test/test_io.py
  requirements_dev.txt
  setup.cfg
Labels: Type: Enhancement
